from wisdem.floating.turbine_semi_instance import TurbineSemiInstance
from floatingse.instance.tlp_instance import TLPInstance
from rotorse import NREL5MW, DTU10MW
import numpy as np

subsave  = 'tlp-soga.save'
turbsave = 'turb-tlp-soga.save'

mytlp = TLPInstance()
mytlp.set_reference('10MW')
mytlp.load(subsave)


# SOGA
mytlp.set_optimizer('soga')
mytlp.set_options({'generations':5000, 'population':50, 'restart':True, 'penalty':True})
mytlp.add_design_variable('fairlead',0.0, 100.0)
mytlp.add_design_variable('fairlead_offset_from_shell',0.0, 5.0)
mytlp.add_design_variable('fairlead_support_wall_thickness',1e-3, 1e-1)
mytlp.add_design_variable('fairlead_support_outer_diameter',1e-2, 5.0)
mytlp.add_design_variable('base_freeboard',0.0, 50.0)
mytlp.add_design_variable('base_section_height',1e-1, 50.0)
mytlp.add_design_variable('base_outer_diameter',2.1, 20.0)
mytlp.add_design_variable('base_wall_thickness',1e-3, 5e-1)
mytlp.add_design_variable('auxiliary_freeboard',0.0, 50.0)
mytlp.add_design_variable('auxiliary_section_height',1e-1, 50.0)
mytlp.add_design_variable('auxiliary_outer_diameter',1.1, 20.0)
mytlp.add_design_variable('auxiliary_wall_thickness',1e-3, 5e-1)
mytlp.add_design_variable('pontoon_outer_diameter', 2e-1, 3.0)
mytlp.add_design_variable('pontoon_wall_thickness', 1e-2, 1e-1)
mytlp.add_design_variable('base_pontoon_attach_lower',-1e2, 1e2)
mytlp.add_design_variable('base_pontoon_attach_upper',-1e2, 1e2)
mytlp.add_design_variable('tower_section_height',1e-1, 100.0)
mytlp.add_design_variable('tower_outer_diameter',1.1, 20.0)
mytlp.add_design_variable('tower_wall_thickness',1e-3, 5e-1)
mytlp.add_design_variable('mooring_line_length', 100.0, 320.0)
mytlp.add_design_variable('anchor_radius', 0.0, 1e2)
mytlp.add_design_variable('mooring_diameter', 0.05, 1.0)
mytlp.add_design_variable('base_permanent_ballast_height', 1e-1, 50.0)
mytlp.add_design_variable('base_stiffener_web_height', 1e-2, 1.0)
mytlp.add_design_variable('base_stiffener_web_thickness', 1e-3, 5e-1)
mytlp.add_design_variable('base_stiffener_flange_width', 1e-2, 5.0)
mytlp.add_design_variable('base_stiffener_flange_thickness', 1e-3, 5e-1)
mytlp.add_design_variable('base_stiffener_spacing', 1e-1, 1e2)
mytlp.add_design_variable('auxiliary_stiffener_web_height', 1e-2, 1.0)
mytlp.add_design_variable('auxiliary_stiffener_web_thickness', 1e-3, 5e-1)
mytlp.add_design_variable('auxiliary_stiffener_flange_width', 1e-2, 5.0)
mytlp.add_design_variable('auxiliary_stiffener_flange_thickness', 1e-3, 5e-1)
mytlp.add_design_variable('auxiliary_stiffener_spacing', 1e-1, 1e2)
mytlp.add_design_variable('auxiliary_permanent_ballast_height', 1e-1, 50.0)
mytlp.add_design_variable('number_of_mooring_lines', 3, 6)
mytlp.add_design_variable('number_of_auxiliary_columns', 3, 6)
mytlp.add_design_variable('outer_cross_pontoons_int', 0, 1)
mytlp.add_design_variable('cross_attachment_pontoons_int', 0, 1)
mytlp.add_design_variable('lower_attachment_pontoons_int', 0, 1)
mytlp.add_design_variable('upper_attachment_pontoons_int', 0, 1)
mytlp.add_design_variable('lower_ring_pontoons_int', 0, 1)
mytlp.add_design_variable('upper_ring_pontoons_int', 0, 1)
mytlp.add_design_variable('radius_to_auxiliary_column', 5.0, 50.0)

#mytlp.evaluate()
mytlp.run()
mytlp.save(subsave)
#mytlp.visualize()#'tlp-soga.jpg')

# Now shift to whole turbine
myturb = TurbineSemiInstance(DTU10MW())
myturb.set_reference('10MW')
for k in myturb.params.keys():
    if mytlp.params.has_key(k):
        myturb.params[k] = mytlp.params[k]

myturb.set_optimizer('soga')
myturb.set_options({'generations':5000, 'population':40, 'restart':False, 'penalty':True})
myturb.add_design_variable('fairlead',0.0, 100.0)
myturb.add_design_variable('fairlead_offset_from_shell',0.0, 5.0)
myturb.add_design_variable('fairlead_support_wall_thickness',1e-3, 1e-1)
myturb.add_design_variable('fairlead_support_outer_diameter',1e-2, 5.0)
myturb.add_design_variable('base_freeboard',0.0, 50.0)
myturb.add_design_variable('base_section_height',1e-1, 50.0)
myturb.add_design_variable('base_outer_diameter',2.1, 20.0)
myturb.add_design_variable('base_wall_thickness',1e-3, 5e-1)
myturb.add_design_variable('auxiliary_freeboard',0.0, 50.0)
myturb.add_design_variable('auxiliary_section_height',1e-1, 50.0)
myturb.add_design_variable('auxiliary_outer_diameter',1.1, 20.0)
myturb.add_design_variable('auxiliary_wall_thickness',1e-3, 5e-1)
myturb.add_design_variable('pontoon_outer_diameter', 2e-1, 3.0)
myturb.add_design_variable('pontoon_wall_thickness', 1e-2, 1e-1)
myturb.add_design_variable('base_pontoon_attach_lower',-1e2, 1e2)
myturb.add_design_variable('base_pontoon_attach_upper',-1e2, 1e2)
myturb.add_design_variable('tower_section_height',1e-1, 100.0)
myturb.add_design_variable('tower_outer_diameter',1.1, 20.0)
myturb.add_design_variable('tower_wall_thickness',1e-3, 5e-1)
myturb.add_design_variable('mooring_line_length', 100.0, 320.0)
myturb.add_design_variable('anchor_radius', 0.0, 1e2)
myturb.add_design_variable('mooring_diameter', 0.05, 1.0)
myturb.add_design_variable('base_permanent_ballast_height', 1e-1, 50.0)
myturb.add_design_variable('base_stiffener_web_height', 1e-2, 1.0)
myturb.add_design_variable('base_stiffener_web_thickness', 1e-3, 5e-1)
myturb.add_design_variable('base_stiffener_flange_width', 1e-2, 5.0)
myturb.add_design_variable('base_stiffener_flange_thickness', 1e-3, 5e-1)
myturb.add_design_variable('base_stiffener_spacing', 1e-1, 1e2)
myturb.add_design_variable('auxiliary_stiffener_web_height', 1e-2, 1.0)
myturb.add_design_variable('auxiliary_stiffener_web_thickness', 1e-3, 5e-1)
myturb.add_design_variable('auxiliary_stiffener_flange_width', 1e-2, 5.0)
myturb.add_design_variable('auxiliary_stiffener_flange_thickness', 1e-3, 5e-1)
myturb.add_design_variable('auxiliary_stiffener_spacing', 1e-1, 1e2)
myturb.add_design_variable('auxiliary_permanent_ballast_height', 1e-1, 50.0)
myturb.add_design_variable('number_of_mooring_lines', 3, 6)
myturb.add_design_variable('number_of_auxiliary_columns', 3, 6)
myturb.add_design_variable('outer_cross_pontoons_int', 0, 1)
myturb.add_design_variable('cross_attachment_pontoons_int', 0, 1)
myturb.add_design_variable('lower_attachment_pontoons_int', 0, 1)
myturb.add_design_variable('upper_attachment_pontoons_int', 0, 1)
myturb.add_design_variable('lower_ring_pontoons_int', 0, 1)
myturb.add_design_variable('upper_ring_pontoons_int', 0, 1)
myturb.add_design_variable('radius_to_auxiliary_column', 5.0, 50.0)

#myturb.evaluate()
myturb.run()
myturb.save(turbsave)
